name: ms_kopalisce_main
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: 7.0.0
  flutter_bloc: 7.0.0
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.2.4
  firebase_core: ^2.3.0
  flutter:
    sdk: flutter
  flutter_flushbar: ^0.0.2
  formz: ^0.4.1
  http: ^0.13.5
  weather_icons: ^3.0.0
  weather_repository:
    path: packages/weather_repository
  coupon_repository:
    git:
      url: https://github.com/jurej1/coupon_repository.git
      ref: master

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true




 