name: price_repository
description: Dart package which manages the price domain.
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cloud_firestore: ^4.3.1
  equatable: ^2.0.5
  firebase_auth: ^4.2.4
  flutter:
    sdk: flutter
