name: weather_repository
description: Dart package which manages the weather domain.
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ^0.13.5

flutter:
  assets:
    - lib/assets/day
    - lib/assets/night